apiVersion: v1
kind: Secret
metadata:
  name: broz-secrets
  namespace: broz-data
type: Opaque
stringData:
  POSTGRES_USER: brozadmin
  POSTGRES_PASSWORD: CHANGE_ME_IN_PRODUCTION
  RABBITMQ_USER: broz
  RABBITMQ_PASS: CHANGE_ME_IN_PRODUCTION
  MINIO_ACCESS_KEY: minioadmin
  MINIO_SECRET_KEY: CHANGE_ME_IN_PRODUCTION
---
apiVersion: v1
kind: Secret
metadata:
  name: broz-app-secrets
  namespace: broz-app
type: Opaque
stringData:
  JWT_SECRET: CHANGE_ME_IN_PRODUCTION
  RESEND_API_KEY: re_CHANGE_ME
  GOOGLE_CLIENT_ID: ""
  GOOGLE_CLIENT_SECRET: ""
  LIVERELAY_API_KEY: CHANGE_ME_IN_PRODUCTION
  LIVERELAY_JWT_SECRET: CHANGE_ME_IN_PRODUCTION
---
# Copy of secrets accessible from broz-app namespace
apiVersion: v1
kind: Secret
metadata:
  name: broz-secrets
  namespace: broz-app
type: Opaque
stringData:
  POSTGRES_USER: brozadmin
  POSTGRES_PASSWORD: CHANGE_ME_IN_PRODUCTION
  RABBITMQ_USER: broz
  RABBITMQ_PASS: CHANGE_ME_IN_PRODUCTION
  MINIO_ACCESS_KEY: minioadmin
  MINIO_SECRET_KEY: CHANGE_ME_IN_PRODUCTION
